'use client';

import React, { useEffect, useState } from 'react';
import { useApp } from '@/context/AppContext';
import { GameItem } from '@/types/game';
import { calculateDiscount, formatGbp, formatTry, getPlatformBadgeColor } from '@/lib/utils';
import { ArrowRight, Coins, Flame, History, ShoppingBag, Sparkles, TrendingDown } from 'lucide-react';

interface DailyTrendsViewProps { onOpenPriceHistory: (game: GameItem) => void; onGoToCatalog: () => void; }
interface TrendData { priceDrops: GameItem[]; under10: GameItem[]; under20: GameItem[]; totalTracked: number; }

function TrendSection({ title, description, icon, games, onOpenPriceHistory }: { title: string; description: string; icon: React.ReactNode; games: GameItem[]; onOpenPriceHistory: (game: GameItem) => void }) {
  const { addToBasket, basket, exchangeRate } = useApp();
  return <section><div className="mb-4 flex items-center gap-3"><div className="rounded-xl border border-zinc-700 bg-zinc-900 p-2 text-blue-400">{icon}</div><div><h3 className="text-lg font-bold text-white">{title}</h3><p className="text-xs text-zinc-400">{description}</p></div></div><div className="grid grid-cols-1 gap-3 min-[390px]:grid-cols-2 lg:grid-cols-3">{games.map((game) => { const inBasket = basket.some((item) => item.game.id === game.id); const discount = calculateDiscount(game.sellPrice, game.originalPrice); const colors = getPlatformBadgeColor(game.platform); return <article key={game.id} className="flex flex-col justify-between rounded-2xl border border-zinc-800 bg-zinc-900 p-3"><div><div className="mb-2 flex items-center justify-between gap-2"><span className={`rounded border px-1.5 py-0.5 text-[10px] font-bold ${colors.bg} ${colors.text} ${colors.border}`}>{game.platform.replace('_', ' ')}</span>{discount > 0 && <span className="rounded-full bg-blue-600 px-2 py-0.5 text-[10px] font-black text-white">-%{discount}</span>}</div><h4 className="line-clamp-2 min-h-10 text-sm font-bold text-white">{game.title}</h4><p className="mt-1 text-[11px] text-zinc-400">{game.genre || 'Konsol oyunu'}</p><div className="mt-3"><strong className="font-mono text-lg text-white">{formatGbp(game.sellPrice)}</strong><span className="ml-2 text-[10px] font-mono text-zinc-400">≈ {formatTry(game.sellPrice * exchangeRate)}</span></div></div><div className="mt-3 flex items-center justify-between border-t border-zinc-800 pt-3"><button onClick={() => onOpenPriceHistory(game)} className="flex items-center gap-1 text-xs text-zinc-400 hover:text-white"><History className="h-3.5 w-3.5" />Geçmiş</button><button onClick={() => addToBasket(game)} className={`rounded-xl px-3 py-1.5 text-xs font-bold ${inBasket ? 'border border-zinc-700 bg-zinc-800 text-zinc-300' : 'bg-blue-600 text-white hover:bg-blue-500'}`}><ShoppingBag className="mr-1 inline h-3.5 w-3.5" />{inBasket ? 'Sepette' : 'Ekle'}</button></div></article>; })}</div></section>;
}

export function DailyTrendsView({ onOpenPriceHistory, onGoToCatalog }: DailyTrendsViewProps) {
  const [trends, setTrends] = useState<TrendData | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const response = await fetch('/api/trends?limit=12', { signal: controller.signal }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Trend verisi alınamadı.'); setTrends(data); } catch (reason) { if ((reason as Error).name !== 'AbortError') setError(reason instanceof Error ? reason.message : 'Trend verisi alınamadı.'); } })(); return () => controller.abort(); }, []);
  if (error) return <div className="rounded-2xl border border-orange-900 bg-orange-950/30 p-6 text-center text-sm text-orange-300">{error}</div>;
  if (!trends) return <div className="py-16 text-center text-sm text-zinc-400">Günlük fırsatlar yükleniyor...</div>;
  return <div className="space-y-8 text-white"><div className="rounded-3xl border border-blue-900/40 bg-gradient-to-br from-blue-950 via-zinc-900 to-zinc-900 p-5 shadow-xl sm:p-8"><div className="inline-flex items-center gap-2 rounded-full border border-blue-500/40 bg-blue-600/30 px-3 py-1 text-xs font-bold text-blue-300"><Flame className="h-3.5 w-3.5 text-amber-400" />Günün fiyat değişimleri</div><h2 className="mt-3 text-xl font-black sm:text-3xl">CeX UK Günlük Fiyat Takibi</h2><p className="mt-2 text-sm leading-relaxed text-zinc-300">Fiyatı düşen oyunları ve bütçe dostu fırsatları, katalogyu tamamen indirmeden inceleyin.</p><div className="mt-4 inline-flex rounded-xl border border-zinc-700 bg-black/50 px-3 py-1.5 text-xs text-zinc-300">Toplam takip edilen: <strong className="ml-1 text-white">{trends.totalTracked} oyun</strong></div></div><TrendSection title="En yüksek fiyat düşüşleri" description="Son fiyatına göre en avantajlı ürünler" icon={<TrendingDown className="h-5 w-5" />} games={trends.priceDrops} onOpenPriceHistory={onOpenPriceHistory} /><TrendSection title="10 £ altı fırsatlar" description="Küçük bütçeyle iyi seçenekler" icon={<Coins className="h-5 w-5 text-emerald-400" />} games={trends.under10} onOpenPriceHistory={onOpenPriceHistory} /><TrendSection title="10–20 £ öne çıkanlar" description="Puanı ve fiyatı dengeli oyunlar" icon={<Sparkles className="h-5 w-5 text-amber-400" />} games={trends.under20} onOpenPriceHistory={onOpenPriceHistory} /><div className="pt-2 text-center"><button onClick={onGoToCatalog} className="inline-flex items-center gap-2 rounded-2xl border border-zinc-700 bg-zinc-800 px-6 py-3 font-bold text-white hover:bg-zinc-700">Tüm kataloğu incele <ArrowRight className="h-4 w-4" /></button></div></div>;
}
